export { default as Hero } from "./Hero"
export { default as Features } from "./Features"
export { default as Roadmap } from "./Roadmap"
export { default as Team } from "./Team"
export { default as Investors } from "./Investors"
export { default as Faq } from "./Faq"
export { default as JoinUs } from "./JoinUs"
